## Wrangle.ipynb

In [1]:
import numpy as np
import seaborn as sns
import scipy.stats as stats
import pandas as pd
import matplotlib.pyplot as plt
import itertools as it
from math import sqrt
# to turn off pink warning boxes basically for display purposes in class
import warnings
warnings.filterwarnings('ignore')

# import splitting and imputing functions
from sklearn.model_selection import train_test_split
from sklearn.impute import SimpleImputer

# import tools for scaling
import sklearn.preprocessing

# classification algorithms
from sklearn.tree import DecisionTreeClassifier, export_text, plot_tree
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LogisticRegression

# linear regression algorithms
from sklearn.linear_model import LinearRegression, LassoLars, TweedieRegressor
# modeling methods
from sklearn.metrics import mean_squared_error
from sklearn.preprocessing import PolynomialFeatures
from sklearn.metrics import explained_variance_score

# classification analysis
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix

# feature selection
from sklearn.feature_selection import SelectKBest, f_regression
from sklearn.feature_selection import RFE

# to see local file system
import os

# import our own modules
import env
import summarize as s
import wrangle as w

# import prep as p

np.random.seed = 9751

# jupyter settings
%matplotlib inline

In [2]:
z = w.get_zillow_data()

In [3]:
z.head().T

,0,1,2,3,4
parcelid,14106617,11614175,11669507,11659397,12804985
heatingorsystemtypeid,NaN,7.0,7.0,2.0,7.0
buildingclasstypeid,NaN,NaN,NaN,NaN,NaN
architecturalstyletypeid,NaN,NaN,NaN,NaN,NaN
airconditioningtypeid,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...
propertylandusedesc,Single Family Residential,Single Family Residential,Single Family Residential,Single Family Residential,Single Family Residential
storytypeid.2,NaN,NaN,NaN,NaN,NaN
storydesc,NaN,NaN,NaN,NaN,NaN
typeconstructiontypeid.2,NaN,NaN,NaN,NaN,NaN
typeconstructiondesc,NaN,NaN,NaN,NaN,NaN

In [ ]:
# this data is a mess because we're required to import all of it.
# first off get rid of all of the duplicate columns

In [34]:
cols = z.columns.tolist()
cols

['parcelid',
 'heatingorsystemtypeid',
 'buildingclasstypeid',
 'architecturalstyletypeid',
 'airconditioningtypeid',
 'id',
 'basementsqft',
 'bathroomcnt',
 'bedroomcnt',
 'buildingqualitytypeid',
 'calculatedbathnbr',
 'decktypeid',
 'finishedfloor1squarefeet',
 'calculatedfinishedsquarefeet',
 'finishedsquarefeet12',
 'finishedsquarefeet50',
 'finishedsquarefeet6',
 'fips',
 'fireplacecnt',
 'fullbathcnt',
 'garagecarcnt',
 'garagetotalsqft',
 'hashottuborspa',
 'latitude',
 'longitude',
 'lotsizesquarefeet',
 'poolcnt',
 'poolsizesum',
 'pooltypeid10',
 'pooltypeid2',
 'pooltypeid7',
 'propertycountylandusecode',
 'propertylandusetypeid',
 'propertyzoningdesc',
 'rawcensustractandblock',
 'regionidcity',
 'regionidcounty',
 'regionidneighborhood',
 'regionidzip',
 'roomcnt',
 'storytypeid',
 'threequarterbathnbr',
 'typeconstructiontypeid',
 'unitcnt',
 'yardbuildingsqft17',
 'yardbuildingsqft26',
 'yearbuilt',
 'numberofstories',
 'fireplaceflag',
 'structuretaxvaluedollarcnt',
 'taxvaluedollarcnt',
 'assessmentyear',
 'landtaxvaluedollarcnt',
 'taxamount',
 'taxdelinquencyflag',
 'taxdelinquencyyear',
 'censustractandblock',
 'airconditioningdesc',
 'architecturalstyledesc',
 'heatingorsystemdesc',
 'id.1',
 'logerror',
 'transactiondate',
 'id.2',
 'logerror.1',
 'transactiondate.1',
 'id.3',
 'airconditioningtypeid.1',
 'bathroomcnt.1',
 'bedroomcnt.1',
 'buildingqualitytypeid.1',
 'calculatedbathnbr.1',
 'decktypeid.1',
 'finishedfloor1squarefeet.1',
 'calculatedfinishedsquarefeet.1',
 'finishedsquarefeet12.1',
 'finishedsquarefeet15.1',
 'finishedsquarefeet50.1',
 'finishedsquarefeet6.1',
 'fips.1',
 'fireplacecnt.1',
 'fullbathcnt.1',
 'garagecarcnt.1',
 'garagetotalsqft.1',
 'hashottuborspa.1',
 'heatingorsystemtypeid.1',
 'latitude.1',
 'longitude.1',
 'lotsizesquarefeet.1',
 'poolcnt.1',
 'pooltypeid10.1',
 'pooltypeid2.1',
 'pooltypeid7.1',
 'propertycountylandusecode.1',
 'propertylandusetypeid.1',
 'propertyzoningdesc.1',
 'rawcensustractandblock.1',
 'regionidcity.1',
 'regionidcounty.1',
 'regionidneighborhood.1',
 'regionidzip.1',
 'roomcnt.1',
 'threequarterbathnbr.1',
 'unitcnt.1',
 'yardbuildingsqft17.1',
 'yearbuilt.1',
 'numberofstories.1',
 'structuretaxvaluedollarcnt.1',
 'taxvaluedollarcnt.1',
 'assessmentyear.1',
 'landtaxvaluedollarcnt.1',
 'taxamount.1',
 'taxdelinquencyflag.1',
 'taxdelinquencyyear.1',
 'censustractandblock.1',
 'propertylandusedesc',
 'storydesc',
 'typeconstructiondesc']

In [ ]:
# make a list of columns with a period in them

In [32]:
# dup_cols = z.T.duplicated()

In [31]:
# dup_cols.info()

In [30]:
# dup_cols

In [23]:
# dup_cols_list = z.columns[dup_cols].tolist()

In [29]:
# dup_cols_list

In [28]:
# z = z.drop(columns=dup_cols_list)
# z.shape

In [27]:
# z.columns.tolist()

In [ ]:
# there still seem to be a lot of columns ending in .* which should
# be dupes. Maybe the dupe finder only eliminated 1 dupe. Try again
# after checking it seems that it eliminated the first dupe, but often
# left one that had a .* and eliminated the one without.
# I don't like this method. Going to go back and get rid of any column
# with a '.'

In [9]:
z_dupes = z[(z.duplicated('parcelid') == True)]['transactiondate']
z_dupes

219      2016-06-23
911             NaN
980             NaN
1928            NaN
2115            NaN
            ...
49520           NaN
49741           NaN
49829           NaN
50904           NaN
51240           NaN
Name: transactiondate, Length: 122, dtype: object

In [4]:
s.summarize(z)

SUMMARY REPORT
=====================================================


Dataframe head:
   parcelid  heatingorsystemtypeid  buildingclasstypeid  \
0  14106617                    NaN                  NaN
1  11614175                    7.0                  NaN
2  11669507                    7.0                  NaN

   architecturalstyletypeid  airconditioningtypeid       id  basementsqft  \
0                       NaN                    NaN  2129300           NaN
1                       NaN                    NaN  1137834           NaN
2                       NaN                    NaN   437335           NaN

   bathroomcnt  bedroomcnt  buildingqualitytypeid  ...  taxamount.1  \
0          2.0         3.0                    NaN  ...      3519.46
1          2.0         3.0                    6.0  ...     13343.01
2          1.0         2.0                    6.0  ...     34606.78

   taxdelinquencyflag.1  taxdelinquencyyear.1  censustractandblock.1  \
0                   NaN                   NaN           6.059110e+13
1                   NaN                   NaN           6.037267e+13
2                   NaN                   NaN           6.037263e+13

   propertylandusetypeid.2        propertylandusedesc  storytypeid.2  \
0                      261  Single Family Residential            NaN
1                      261  Single Family Residential            NaN
2                      261  Single Family Residential            NaN

   storydesc  typeconstructiontypeid.2  typeconstructiondesc
0        NaN                       NaN                   NaN
1        NaN                       NaN                   NaN
2        NaN                       NaN                   NaN

[3 rows x 133 columns]
=====================================================


Dataframe info:
<class 'pandas.core.frame.DataFrame'>
Int64Index: 52442 entries, 0 to 52441
Columns: 133 entries, parcelid to typeconstructiondesc
dtypes: float64(114), int64(5), object(14)
memory usage: 53.6+ MB
None
=====================================================


Dataframe Description:
           parcelid  heatingorsystemtypeid  buildingclasstypeid  \
count  5.244200e+04           33935.000000                  0.0
mean   1.299920e+07               3.966288                  NaN
std    3.411462e+06               2.562506                  NaN
min    1.071186e+07               1.000000                  NaN
25%    1.151030e+07               2.000000                  NaN
50%    1.257766e+07               2.000000                  NaN
75%    1.412956e+07               7.000000                  NaN
max    1.676878e+08              24.000000                  NaN

       architecturalstyletypeid  airconditioningtypeid            id  \
count                  70.00000           13638.000000  5.244200e+04
mean                    7.10000               2.438041  1.497298e+06
std                     2.66567               3.846176  8.594551e+05
min                     2.00000               1.000000  3.490000e+02
25%                     7.00000               1.000000  7.579560e+05
50%                     7.00000               1.000000  1.500836e+06
75%                     7.00000               1.000000  2.241564e+06
max                    21.00000              13.000000  2.982270e+06

       basementsqft   bathroomcnt    bedroomcnt  buildingqualitytypeid  ...  \
count     47.000000  52442.000000  52442.000000           33740.000000  ...
mean     678.978723      2.299416      3.300694               6.264167  ...
std      711.825226      1.022767      0.949090               1.716162  ...
min       38.000000      0.000000      0.000000               1.000000  ...
25%      263.500000      2.000000      3.000000               5.000000  ...
50%      512.000000      2.000000      3.000000               6.000000  ...
75%      809.500000      3.000000      4.000000               8.000000  ...
max     3560.000000     18.000000     14.000000              12.000000  ...

       structuretaxvaluedollarcnt.1  taxvaluedollarcnt.1  assessmentyear.1  \
count                  5.230100e+04         5.236600e+04      52366.000000
mean                   1.872991e+05         4.946575e+05       2014.999981
std                    2.388243e+05         6.939866e+05          0.004370
min                    1.280000e+02         3.206000e+03       2014.000000
25%                    7.334900e+04         1.786955e+05       2015.000000
50%                    1.259600e+05         3.504160e+05       2015.000000
75%                    2.170000e+05         5.827255e+05       2015.000000
max                    9.027236e+06         4.832429e+07       2015.000000

       landtaxvaluedollarcnt.1    taxamount.1  taxdelinquencyyear.1  \
count             5.236600e+04   52365.000000           2076.000000
mean              3.075910e+05    6414.558665             14.101638
std               5.250637e+05    8705.450474              2.396539
min               1.590000e+02      49.080000              4.000000
25%               6.811600e+04    2641.390000             14.000000
50%               2.015190e+05    4620.780000             15.000000
75%               3.805475e+05    7336.670000             15.000000
max               4.821689e+07  586639.300000             99.000000

       censustractandblock.1  propertylandusetypeid.2  storytypeid.2  \
count           5.228100e+04                  52442.0           47.0
mean            6.050244e+13                    261.0            7.0
std             1.859691e+12                      0.0            0.0
min             6.037101e+13                    261.0            7.0
25%             6.037401e+13                    261.0            7.0
50%             6.037620e+13                    261.0            7.0
75%             6.059042e+13                    261.0            7.0
max             4.830301e+14                    261.0            7.0

       typeconstructiontypeid.2
count                 76.000000
mean                   5.973684
std                    0.229416
min                    4.000000
25%                    6.000000
50%                    6.000000
75%                    6.000000
max                    6.000000

[8 rows x 119 columns]
=====================================================
DataFrame value counts:
14106617    1
11614175    1
11669507    1
11659397    1
12804985    1
           ..
12685414    1
11137574    1
11549082    1
10875475    1
12858860    1
Name: parcelid, Length: 52320, dtype: int64

7.0     12565
2.0     20736
6.0       517
20.0       85
13.0       16
18.0        6
1.0         7
10.0        2
24.0        1
Name: heatingorsystemtypeid, dtype: int64

Series([], Name: buildingclasstypeid, dtype: int64)

7.0     62
3.0      3
8.0      1
21.0     2
2.0      2
Name: architecturalstyletypeid, dtype: int64

1.0     11895
13.0     1568
5.0       159
11.0       16
Name: airconditioningtypeid, dtype: int64

2129300    1
1137834    1
437335     1
407261     1
1521160    1
          ..
992862     1
181844     1
884106     1
1776968    1
2454764    1
Name: id, Length: 52320, dtype: int64

515.0     2
512.0     1
352.0     1
600.0     1
314.0     1
786.0     1
405.0     1
112.0     1
912.0     2
168.0     1
819.0     1
604.0     1
669.0     1
1969.0    1
1252.0    1
200.0     1
588.0     1
204.0     1
300.0     1
280.0     1
38.0      1
394.0     1
380.0     1
126.0     1
100.0     2
1416.0    1
254.0     1
396.0     1
1218.0    1
384.0     1
90.0      1
900.0     2
1809.0    1
3112.0    1
640.0     2
252.0     1
273.0     2
224.0     1
3560.0    1
800.0     1
645.0     1
Name: basementsqft, dtype: int64

2.0     21893
1.0      9568
3.0     10674
2.5      3934
4.5       687
4.0      2227
3.5       918
5.0       803
1.5       841
8.0        53
5.5       224
6.5        47
6.0       322
0.0       121
7.0        88
9.0        13
18.0        1
13.0        1
10.0        5
7.5        16
8.5         3
11.0        3
Name: bathroomcnt, dtype: int64

3.0     23359
2.0      8340
4.0     15241
5.0      3973
1.0       612
7.0       106
6.0       635
0.0       137
8.0        24
9.0         8
14.0        1
12.0        3
10.0        2
11.0        1
Name: bedroomcnt, dtype: int64

6.0     10289
8.0      8244
4.0      8156
7.0      3427
5.0      1513
9.0      1121
11.0      514
3.0       152
10.0      230
12.0       81
1.0         8
2.0         5
Name: buildingqualitytypeid, dtype: int64

2.0     21893
1.0      9568
3.0     10674
2.5      3926
4.5       687
4.0      2227
3.5       918
5.0       803
1.5       834
8.0        53
5.5       223
6.5        47
6.0       322
7.0        88
9.0        13
18.0        1
13.0        1
10.0        5
7.5        16
8.5         3
11.0        3
Name: calculatedbathnbr, dtype: int64

66.0    389
Name: decktypeid, dtype: int64

741.0     1
1365.0    5
570.0     1
1460.0    6
1674.0    2
         ..
2766.0    1
2590.0    1
1869.0    1
2127.0    1
1717.0    1
Name: finishedfloor1squarefeet, Length: 1553, dtype: int64

1409.0     25
1614.0     27
995.0      13
2112.0     18
1348.0     43
           ..
6138.0      1
4562.0      1
4116.0      1
5433.0      1
10312.0     1
Name: calculatedfinishedsquarefeet, Length: 4723, dtype: int64

1409.0     25
1614.0     27
995.0      13
2112.0     18
1348.0     43
           ..
4562.0      1
4116.0      1
5433.0      1
10312.0     1
380.0       1
Name: finishedsquarefeet12, Length: 4716, dtype: int64

Series([], Name: finishedsquarefeet13, dtype: int64)

Series([], Name: finishedsquarefeet15, dtype: int64)

741.0     1
1365.0    5
570.0     1
1460.0    6
1674.0    2
         ..
5062.0    1
2766.0    1
1869.0    1
2127.0    1
1717.0    1
Name: finishedsquarefeet50, Length: 1572, dtype: int64

601.0     1
904.0     1
1804.0    1
935.0     2
664.0     1
         ..
1719.0    1
2423.0    1
740.0     1
1296.0    1
2796.0    1
Name: finishedsquarefeet6, Length: 155, dtype: int64

6059.0    14136
6037.0    33910
6111.0     4396
Name: fips, dtype: int64

2.0     945
1.0    6031
3.0     229
4.0      35
5.0       3
Name: fireplacecnt, dtype: int64

2.0     25831
1.0     10402
3.0     11601
4.0      2915
5.0      1022
8.0        56
6.0       359
7.0        96
9.0        13
18.0        1
13.0        1
10.0        5
11.0        3
Name: fullbathcnt, dtype: int64

2.0     14803
1.0      2202
0.0        65
3.0       621
4.0       254
8.0         2
6.0        13
9.0         2
5.0        45
7.0         3
11.0        1
10.0        3
13.0        1
14.0        1
Name: garagecarcnt, dtype: int64

413.0      45
420.0     550
568.0      25
706.0      12
436.0      63
         ...
950.0       1
2901.0      1
1071.0      1
1044.0      1
136.0       1
Name: garagetotalsqft, Length: 839, dtype: int64

1.0    1515
Name: hashottuborspa, dtype: int64

33814427.0    1
34045401.0    2
34042803.0    1
34054923.0    1
33986985.0    1
             ..
33803690.0    1
34367884.0    1
33998036.0    1
34219660.0    1
33989244.0    1
Name: latitude, Length: 50478, dtype: int64

-118033546.0    1
-118433920.0    1
-118518413.0    1
-118475506.0    1
-118069441.0    1
               ..
-118379902.0    1
-118539868.0    1
-118456684.0    1
-118391472.0    1
-117835658.0    1
Name: longitude, Length: 50764, dtype: int64

6000.0     876
6767.0      12
4696.0       5
6999.0      39
6249.0      33
          ...
22472.0      1
3783.0       1
15423.0      1
22449.0      1
28579.0      1
Name: lotsizesquarefeet, Length: 14292, dtype: int64

1.0    11097
Name: poolcnt, dtype: int64

377.0     2
400.0    38
800.0    25
290.0     1
560.0     8
         ..
582.0     1
129.0     1
24.0      1
756.0     1
561.0     1
Name: poolsizesum, Length: 262, dtype: int64

1.0    444
Name: pooltypeid10, dtype: int64

1.0    1071
Name: pooltypeid2, dtype: int64

1.0    10010
Name: pooltypeid7, dtype: int64

0100    26782
122     13067
0101     6413
1111     3362
1        1069
1110     1026
0104      369
010G       94
0103       91
0108       57
010M       53
0109       18
1112        8
0113        6
0110        6
0141        4
0102        3
0105        3
0111        2
0130        2
010V        2
0114        1
0115        1
0131        1
010L        1
0133        1
Name: propertycountylandusecode, dtype: int64

261.0    52442
Name: propertylandusetypeid, dtype: int64

LAR1         6498
LARS         1385
LBR1N        1111
SCUR2         712
LARE11        612
             ...
LCRAL2          1
LRRA 6000       1
TORR            1
WHR112          1
LCD22*          1
Name: propertyzoningdesc, Length: 1286, dtype: int64

6.059110e+07    13
6.037267e+07     1
6.037263e+07     1
6.037264e+07     1
6.037501e+07     2
                ..
6.037271e+07     1
6.037103e+07     1
6.037504e+07     1
6.037555e+07     1
6.037670e+07     1
Name: rawcensustractandblock, Length: 31440, dtype: int64

44833.0       252
12447.0     11452
396556.0       95
46080.0       186
54311.0       871
            ...
31134.0         2
118880.0        5
10815.0         1
32927.0         3
21395.0         1
Name: regionidcity, Length: 175, dtype: int64

1286.0    14136
3101.0    33910
2061.0     4396
Name: regionidcounty, dtype: int64

118887.0     37
19810.0     228
113910.0    193
268473.0    126
48200.0     131
           ...
273096.0      1
47913.0       1
761215.0      1
764104.0      1
763090.0      1
Name: regionidneighborhood, Length: 437, dtype: int64

96185.0    263
96006.0     36
96120.0    216
96030.0    226
96174.0    124
          ...
97092.0      1
95996.0      2
96038.0      1
97088.0      1
96039.0      2
Name: regionidzip, Length: 381, dtype: int64

5.0      1890
0.0     37853
4.0       521
6.0      3982
12.0       35
8.0      2813
7.0      3616
10.0      339
9.0      1176
3.0        79
2.0        12
11.0      108
13.0       10
14.0        6
15.0        1
1.0         1
Name: roomcnt, dtype: int64

7.0    47
Name: storytypeid, dtype: int64

1.0    6645
2.0      70
3.0       8
7.0       1
Name: threequarterbathnbr, dtype: int64

6.0    75
4.0     1
Name: typeconstructiontypeid, dtype: int64

1.0    33817
2.0       29
3.0        1
Name: unitcnt, dtype: int64

263.0     4
190.0     6
432.0     8
400.0    37
230.0     7
         ..
339.0     1
513.0     1
562.0     1
706.0     1
17.0      1
Name: yardbuildingsqft17, Length: 504, dtype: int64

105.0    1
60.0     1
91.0     1
66.0     1
30.0     1
752.0    1
113.0    1
300.0    2
37.0     1
39.0     1
16.0     1
160.0    1
320.0    1
648.0    1
108.0    1
120.0    3
196.0    1
218.0    1
491.0    1
240.0    2
231.0    1
462.0    1
21.0     1
336.0    1
868.0    1
45.0     1
169.0    1
28.0     1
140.0    1
12.0     1
174.0    1
144.0    1
576.0    1
72.0     1
250.0    1
461.0    1
133.0    1
56.0     2
71.0     1
204.0    1
216.0    1
448.0    2
41.0     1
384.0    1
49.0     1
88.0     1
314.0    1
414.0    1
48.0     1
200.0    1
292.0    1
486.0    1
180.0    1
368.0    1
195.0    1
360.0    1
284.0    1
Name: yardbuildingsqft26, dtype: int64

1962.0    1000
1923.0     531
1941.0     524
1936.0     237
1950.0    1608
          ...
1882.0       1
1878.0       1
1887.0       3
1894.0       1
1880.0       1
Name: yearbuilt, Length: 133, dtype: int64

1.0    8890
2.0    5319
3.0     352
6.0       1
Name: numberofstories, dtype: int64

1.0    81
Name: fireplaceflag, dtype: int64

106809.0     1
221365.0     1
1437000.0    1
62318.0      6
79114.0      1
            ..
113727.0     1
45017.0      1
69241.0      1
353181.0     1
113744.0     1
Name: structuretaxvaluedollarcnt, Length: 37333, dtype: int64

295907.0     1
1106837.0    2
2883731.0    1
169371.0     1
244578.0     1
            ..
570506.0     1
277519.0     1
149698.0     1
126074.0     1
619248.0     1
Name: taxvaluedollarcnt, Length: 38942, dtype: int64

2016.0    52442
Name: assessmentyear, dtype: int64

189098.0     1
885472.0     1
1446731.0    2
107053.0     1
165464.0     1
            ..
180100.0     1
217325.0     1
167476.0     1
167640.0     1
339400.0     1
Name: landtaxvaluedollarcnt, Length: 36912, dtype: int64

3519.46     1
13343.01    1
34606.78    1
2193.13     1
3215.14     1
           ..
3046.03     1
1781.54     1
24472.07    1
4614.89     1
7250.46     1
Name: taxamount, Length: 50834, dtype: int64

Y    2079
Name: taxdelinquencyflag, dtype: int64

15.0    1131
14.0     560
10.0      47
11.0      79
9.0       33
13.0     129
7.0        8
8.0        8
12.0      81
99.0       1
6.0        1
4.0        1
Name: taxdelinquencyyear, dtype: int64

6.059110e+13    13
6.037267e+13     1
6.037263e+13     1
6.037264e+13     1
6.037501e+13     2
                ..
6.037271e+13     1
6.037103e+13     1
6.037504e+13     1
6.037555e+13     1
6.037670e+13     1
Name: censustractandblock, Length: 31404, dtype: int64

Central      11895
Yes           1568
None           159
Wall Unit       16
Name: airconditioningdesc, dtype: int64

Contemporary     62
Cape Cod          3
Ranch/Rambler     2
Bungalow          2
Conventional      1
Name: architecturalstyledesc, dtype: int64

Series([], Name: buildingclassdesc, dtype: int64)

Central       20736
Floor/Wall    12565
Forced air      517
Solar            85
None             16
Baseboard         7
Radiant           6
Gravity           2
Yes               1
Name: heatingorsystemdesc, dtype: int64

2025.0     1
1751.0     1
662.0      1
2992.0     1
1935.0     1
          ..
11296.0    1
32442.0    1
26457.0    1
77142.0    1
71119.0    1
Name: id.1, Length: 1659, dtype: int64

-0.0629    1
-0.0131    4
-0.0419    6
 0.0334    8
 0.2844    4
          ..
 0.3832    1
 0.3322    1
 0.7246    1
-0.4020    1
 0.3887    1
Name: logerror, Length: 598, dtype: int64

2016-04-29    17
2016-05-13    16
2016-07-21    16
2016-07-08    15
2016-06-10    15
              ..
2016-05-15     1
2016-01-01     1
2016-01-18     1
2016-01-10     1
2016-09-25     1
Name: transactiondate, Length: 252, dtype: int64

1949     1
2575     1
4644     1
4927     1
5056     1
        ..
77143    1
77309    1
77348    1
77451    1
77556    1
Name: id.2, Length: 52441, dtype: int64

-0.014369    1
-0.097205    1
 0.106706    1
-0.045635    1
-0.223649    1
            ..
-0.076127    1
-0.006188    1
-0.027563    1
-0.015941    1
 0.027986    1
Name: logerror.1, Length: 52180, dtype: int64

2017-06-30    810
2017-04-28    617
2017-05-31    566
2017-07-28    546
2017-08-31    528
             ...
2017-05-20      1
2017-04-08      1
2017-05-07      1
2017-03-12      1
2017-09-25      1
Name: transactiondate.1, Length: 257, dtype: int64

2123186    1
1134589    1
436000     1
406018     1
1516845    1
          ..
990005     1
181262     1
881553     1
1771871    1
2447711    1
Name: id.3, Length: 52320, dtype: int64

1.0     11822
13.0     1568
5.0       159
11.0       16
Name: airconditioningtypeid.1, dtype: int64

7.0     62
3.0      3
8.0      1
21.0     2
2.0      2
Name: architecturalstyletypeid.1, dtype: int64

515.0     2
512.0     1
352.0     1
600.0     1
314.0     1
786.0     1
405.0     1
112.0     1
912.0     2
168.0     1
819.0     1
604.0     1
669.0     1
1969.0    1
1252.0    1
200.0     1
588.0     1
204.0     1
300.0     1
280.0     1
38.0      1
394.0     1
380.0     1
126.0     1
100.0     2
1416.0    1
254.0     1
396.0     1
1218.0    1
384.0     1
90.0      1
900.0     2
1809.0    1
3112.0    1
640.0     2
252.0     1
273.0     2
224.0     1
3560.0    1
800.0     1
645.0     1
Name: basementsqft.1, dtype: int64

2.0     21898
1.0      9561
3.0     10628
2.5      3928
4.5       662
4.0      2197
3.5       894
5.0       792
1.5       841
8.0        53
5.5       215
6.5        43
6.0       317
0.0       210
7.0        86
9.0        13
18.0        1
13.0        1
10.0        5
7.5        17
11.0        3
8.5         1
Name: bathroomcnt.1, dtype: int64

3.0     23345
2.0      8347
4.0     15155
5.0      3929
1.0       603
7.0       106
6.0       627
0.0       220
8.0        23
9.0         8
10.0        2
11.0        1
Name: bedroomcnt.1, dtype: int64

Series([], Name: buildingclasstypeid.1, dtype: int64)

7.0     20086
4.0     11686
1.0      1124
10.0      730

In [5]:
z.shape

(52442, 133)

In [6]:
z.parcelid.nunique()

52320